export { ASSEMBLY_SERVICE, SOURCE_PROTOCOL_VERSION, RequestSourceRegistry } from './registry.js'
export { registerBuiltinSources, createDefaultRegistry } from './builtin-sources.js'
export { assembleRequest, assembleRequestAsync, textOf } from './assemble.js'
export { FORMAT, BUILTINS, normalizePreset } from './model.js'
export { normalizeLayout, describeResourceLayout, withBlockMove } from './resource-layout.js'
